### ISSUE TITLE
Correlate with education level (number of people holding a degree or above)

### ISSUE THREAD

**Issue by CristianCantoro** [gedankenstuecke/scihub_analysis#5]
Hi,

I would expect to see some correlation between, say, the portion of people in a country holding a degree and the number of downloads. can you check it, please?

**Comment by gedankenstuecke** [comment]
Thanks for the suggestion. I couldn't find any data on the percent of people holding a degree in the World Bank data. But I found [this data about % GDP spending on education](http://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS), which is the closest I got. The data is pretty sparse in principle, but I used the 2009 data which seemed to be most filled. 

![screen shot 2016-05-03 at 17 24 23](https://cloud.githubusercontent.com/assets/674899/14988399/ebdde1ee-1153-11e6-8279-6bdf13c45c6b.png)

There seems to be little correlation between those two. On the Y-Axis you see the Downloads per 1,000 People, corrected for GDP size. If you find data for the % of poeple with a degree I'm happy to run it again. 👍 😃
